-- MySQL Script generated by MySQL Workbench
-- Fri Sep 15 08:01:37 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`crs_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crs_curso` (
  `crs_id_curso` INT NOT NULL AUTO_INCREMENT,
  `crs_ds_curso` VARCHAR(45) NOT NULL,
  `crs_vl_curso` DOUBLE NOT NULL,
  `crs_id_turma` INT NOT NULL,
  PRIMARY KEY (`crs_id_curso`),
  UNIQUE INDEX `crs_id_curso_UNIQUE` (`crs_id_curso` ASC),
  UNIQUE INDEX `crs_ds_curso_UNIQUE` (`crs_ds_curso` ASC),
  UNIQUE INDEX `crs_vl_curso_UNIQUE` (`crs_vl_curso` ASC),
  UNIQUE INDEX `crs_id_turma_UNIQUE` (`crs_id_turma` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dis_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dis_disciplina` (
  `dis_ds_disciplina` VARCHAR(45) NOT NULL,
  `dis_carga_horaria` DOUBLE NOT NULL,
  `dis_id_disciplina` INT NOT NULL,
  `dis_disciplinacol` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `atp_ds_atividade_UNIQUE` (`dis_ds_disciplina` ASC),
  UNIQUE INDEX `atp_carga_horaria_UNIQUE` (`dis_carga_horaria` ASC),
  UNIQUE INDEX `dis_disciplinacol_UNIQUE` (`dis_disciplinacol` ASC),
  PRIMARY KEY (`dis_disciplinacol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ser_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ser_serie` (
  `ser_id_serie` INT NOT NULL AUTO_INCREMENT,
  `ser_ds_serie` VARCHAR(45) NOT NULL,
  `ser_periodo_letivo` VARCHAR(8) NULL,
  `ser_id_aluno` INT NOT NULL,
  `crs_curso_crs_id_curso` INT NOT NULL,
  PRIMARY KEY (`ser_id_serie`),
  UNIQUE INDEX `tur_id_turma_UNIQUE` (`ser_id_serie` ASC),
  UNIQUE INDEX `tur_ds_turma_UNIQUE` (`ser_ds_serie` ASC),
  INDEX `fk_ser_serie_crs_curso1_idx` (`crs_curso_crs_id_curso` ASC),
  CONSTRAINT `fk_ser_serie_crs_curso1`
    FOREIGN KEY (`crs_curso_crs_id_curso`)
    REFERENCES `mydb`.`crs_curso` (`crs_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alu_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alu_aluno` (
  `alu_nu_matricula` INT NOT NULL AUTO_INCREMENT,
  `alu_nm_aluno` VARCHAR(60) NOT NULL,
  `alu_nm_pai` VARCHAR(60) NULL,
  `alu_nm_mae` VARCHAR(60) NULL,
  `alu_dt_nascimento` DATETIME NULL,
  `alu_nu_cpf_pai` INT NULL,
  `alu_nu_cpf_mae` INT NULL,
  `ser_serie_ser_id_serie` INT NOT NULL,
  PRIMARY KEY (`alu_nu_matricula`, `ser_serie_ser_id_serie`),
  UNIQUE INDEX `alu_nu_matricula_UNIQUE` (`alu_nu_matricula` ASC),
  INDEX `fk_alu_aluno_ser_serie1_idx` (`ser_serie_ser_id_serie` ASC),
  CONSTRAINT `fk_alu_aluno_ser_serie1`
    FOREIGN KEY (`ser_serie_ser_id_serie`)
    REFERENCES `mydb`.`ser_serie` (`ser_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pro_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pro_professor` (
  `pro_nu_matricula` INT NOT NULL AUTO_INCREMENT,
  `pro_nm_professor` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`pro_nu_matricula`),
  UNIQUE INDEX `doc_nu_matricula_UNIQUE` (`pro_nu_matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tur_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tur_turma` (
  `tur_id_serie` INT NOT NULL,
  `tur_id_disciplina` INT NOT NULL,
  `tur_id_turma` INT NOT NULL,
  PRIMARY KEY (`tur_id_serie`),
  CONSTRAINT `fk_serie_disciplina_ser_serie1`
    FOREIGN KEY (`tur_id_serie`)
    REFERENCES `mydb`.`ser_serie` (`ser_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`not_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`not_nota` (
  `not_id_nota` INT NOT NULL AUTO_INCREMENT,
  `not_vl_nota` DOUBLE NOT NULL,
  `not_ds_unidade` VARCHAR(45) NULL,
  `not_ch_final` BINARY(1) NULL,
  `not_nu_matricula_aluno` INT NULL,
  `tur_turma_tur_id_serie` INT NOT NULL,
  INDEX `fk_not_nota_alu_aluno1_idx` (`not_nu_matricula_aluno` ASC),
  INDEX `fk_not_nota_tur_turma1_idx` (`tur_turma_tur_id_serie` ASC),
  PRIMARY KEY (`not_id_nota`),
  CONSTRAINT `fk_not_nota_alu_aluno1`
    FOREIGN KEY (`not_nu_matricula_aluno`)
    REFERENCES `mydb`.`alu_aluno` (`alu_nu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_not_nota_tur_turma1`
    FOREIGN KEY (`tur_turma_tur_id_serie`)
    REFERENCES `mydb`.`tur_turma` (`tur_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`his_historico_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`his_historico_escolar` (
  `his_id_historico` INT NOT NULL AUTO_INCREMENT,
  `his_id_disciplina` INT NOT NULL,
  `his_vl_resultado` DOUBLE NOT NULL,
  `his_periodo_letivo` VARCHAR(5) NOT NULL,
  `his_id_resultado_aluno` INT NOT NULL,
  `his_nu_matricula_aluno` INT NOT NULL,
  `not_nota_not_id_nota` INT NOT NULL,
  PRIMARY KEY (`his_id_historico`, `not_nota_not_id_nota`),
  INDEX `fk_his_historico_escolar_not_nota1_idx` (`not_nota_not_id_nota` ASC),
  CONSTRAINT `fk_his_historico_escolar_not_nota1`
    FOREIGN KEY (`not_nota_not_id_nota`)
    REFERENCES `mydb`.`not_nota` (`not_id_nota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aul_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aul_aula` (
  `aul_id_aula` INT NOT NULL AUTO_INCREMENT,
  `aul_id_disciplina` INT NOT NULL,
  `aul_dt_aula` DATETIME NOT NULL,
  `aul_nu_aula` INT NOT NULL,
  `tur_turma_tur_id_serie` INT NOT NULL,
  UNIQUE INDEX `au_id_aula_UNIQUE` (`aul_id_aula` ASC),
  PRIMARY KEY (`aul_id_aula`),
  INDEX `fk_aul_aula_tur_turma1_idx` (`tur_turma_tur_id_serie` ASC),
  CONSTRAINT `fk_aul_aula_tur_turma1`
    FOREIGN KEY (`tur_turma_tur_id_serie`)
    REFERENCES `mydb`.`tur_turma` (`tur_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fra_frequencia_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fra_frequencia_aluno` (
  `fra_id_registro_presenca` INT NOT NULL AUTO_INCREMENT,
  `fra_ch_presenca` BINARY(1) NULL,
  `fra_nu_matricula_aluno` INT NULL,
  `aul_aula_aul_id_aula` INT NOT NULL,
  PRIMARY KEY (`fra_id_registro_presenca`),
  UNIQUE INDEX `rpa_id_presenca_UNIQUE` (`fra_id_registro_presenca` ASC),
  INDEX `fk_fra_frequencia_aluno_aul_aula1_idx` (`aul_aula_aul_id_aula` ASC),
  CONSTRAINT `fk_fra_frequencia_aluno_aul_aula1`
    FOREIGN KEY (`aul_aula_aul_id_aula`)
    REFERENCES `mydb`.`aul_aula` (`aul_id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tur_turma_has_pro_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tur_turma_has_pro_professor` (
  `tur_turma_tur_id_serie` INT NOT NULL,
  `pro_professor_pro_nu_matricula` INT NOT NULL,
  PRIMARY KEY (`tur_turma_tur_id_serie`, `pro_professor_pro_nu_matricula`),
  INDEX `fk_tur_turma_has_pro_professor_pro_professor1_idx` (`pro_professor_pro_nu_matricula` ASC),
  INDEX `fk_tur_turma_has_pro_professor_tur_turma1_idx` (`tur_turma_tur_id_serie` ASC),
  CONSTRAINT `fk_tur_turma_has_pro_professor_tur_turma1`
    FOREIGN KEY (`tur_turma_tur_id_serie`)
    REFERENCES `mydb`.`tur_turma` (`tur_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tur_turma_has_pro_professor_pro_professor1`
    FOREIGN KEY (`pro_professor_pro_nu_matricula`)
    REFERENCES `mydb`.`pro_professor` (`pro_nu_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dis_disciplina_has_tur_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dis_disciplina_has_tur_turma` (
  `dis_disciplina_dis_disciplinacol` INT NOT NULL,
  `tur_turma_tur_id_serie` INT NOT NULL,
  PRIMARY KEY (`dis_disciplina_dis_disciplinacol`, `tur_turma_tur_id_serie`),
  INDEX `fk_dis_disciplina_has_tur_turma_tur_turma1_idx` (`tur_turma_tur_id_serie` ASC),
  INDEX `fk_dis_disciplina_has_tur_turma_dis_disciplina1_idx` (`dis_disciplina_dis_disciplinacol` ASC),
  CONSTRAINT `fk_dis_disciplina_has_tur_turma_dis_disciplina1`
    FOREIGN KEY (`dis_disciplina_dis_disciplinacol`)
    REFERENCES `mydb`.`dis_disciplina` (`dis_disciplinacol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dis_disciplina_has_tur_turma_tur_turma1`
    FOREIGN KEY (`tur_turma_tur_id_serie`)
    REFERENCES `mydb`.`tur_turma` (`tur_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


