-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 19:18:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `valor_curso` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `crs_id_curso_UNIQUE` (`id` ASC),
  UNIQUE INDEX `crs_ds_curso_UNIQUE` (`nome_curso` ASC),
  UNIQUE INDEX `crs_vl_curso_UNIQUE` (`valor_curso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `nm_disciplina` VARCHAR(45) NOT NULL,
  `carga_horaria` DOUBLE NOT NULL,
  `id_curso` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `atp_ds_atividade_UNIQUE` (`nm_disciplina` ASC),
  UNIQUE INDEX `atp_carga_horaria_UNIQUE` (`carga_horaria` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`serie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `periodo_letivo` VARCHAR(8) NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `curso_id`),
  UNIQUE INDEX `tur_id_turma_UNIQUE` (`id` ASC),
  UNIQUE INDEX `tur_ds_turma_UNIQUE` (`nome` ASC),
  INDEX `fk_serie_curso1_idx` (`curso_id` ASC),
  CONSTRAINT `fk_serie_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `nome_pai` VARCHAR(60) NULL,
  `nome_mae` VARCHAR(60) NULL,
  `data_nascimento` DATETIME NULL,
  `cpf_pai` INT NULL,
  `cpf_mae` INT NULL,
  `rg_aluno` INT NULL,
  `serie_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `alu_nu_matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_aluno_serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_aluno_serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `mydb`.`serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professor` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf_professor` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `doc_nu_matricula_UNIQUE` (`matricula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historico_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historico_escolar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT NOT NULL,
  `valor_resultado` DOUBLE NOT NULL,
  `periodo_letivo` VARCHAR(5) NOT NULL,
  `matricula_aluno` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_escolar_aluno1_idx` (`matricula_aluno` ASC),
  CONSTRAINT `fk_historico_escolar_aluno1`
    FOREIGN KEY (`matricula_aluno`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `serie_id` INT NOT NULL,
  PRIMARY KEY (`id`, `serie_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_turma_serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_turma_serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `mydb`.`serie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_disciplina` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `unidade` VARCHAR(45) NULL,
  `matricula_aluno` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rac_id_resultado_aluno_curso_UNIQUE` (`id` ASC),
  INDEX `fk_not_nota_serie_disciplina1_idx` (`id_turma` ASC),
  INDEX `fk_not_nota_alu_aluno1_idx` (`matricula_aluno` ASC),
  CONSTRAINT `fk_not_nota_serie_disciplina1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_not_nota_alu_aluno1`
    FOREIGN KEY (`matricula_aluno`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aula` (
  `id` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `data_aula` DATETIME NOT NULL,
  `numero_aula` INT NOT NULL,
  UNIQUE INDEX `au_id_aula_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_aul_aula_serie_disciplina1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_aul_aula_serie_disciplina1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `mydb`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frequencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_aula` INT NOT NULL,
  `ch_presenca` BINARY(1) NULL,
  `matricula_aluno` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rpa_id_presenca_UNIQUE` (`id` ASC),
  INDEX `fk_fra_frequencia_aluno_aul_aula1_idx` (`id_aula` ASC),
  INDEX `fk_fra_frequencia_aluno_alu_aluno1_idx` (`matricula_aluno` ASC),
  CONSTRAINT `fk_fra_frequencia_aluno_aul_aula1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `mydb`.`aula` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fra_frequencia_aluno_alu_aluno1`
    FOREIGN KEY (`matricula_aluno`)
    REFERENCES `mydb`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_has_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_has_professor` (
  `turma_id_serie` INT NOT NULL,
  `professor_matricula` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_turma_has_professor_professor1_idx` (`professor_matricula` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_turma_has_professor_professor1`
    FOREIGN KEY (`professor_matricula`)
    REFERENCES `mydb`.`professor` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma_has_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma_has_disciplina` (
  `turma_id` INT NOT NULL,
  `turma_serie_id` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  PRIMARY KEY (`turma_id`, `disciplina_id`, `turma_serie_id`),
  INDEX `fk_turma_has_disciplina_disciplina1_idx` (`disciplina_id` ASC),
  INDEX `fk_turma_has_disciplina_turma1_idx` (`turma_id` ASC, `turma_serie_id` ASC),
  CONSTRAINT `fk_turma_has_disciplina_turma1`
    FOREIGN KEY (`turma_id` , `turma_serie_id`)
    REFERENCES `mydb`.`turma` (`id` , `serie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `mydb`.`disciplina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
